CREATE TABLE PERSONS
(
    NAME           VARCHAR(32),
    SURNAME        VARCHAR(32),
    AGE            VARCHAR(32),
    PHONE_NUMBER   VARCHAR(32),
    CITY_OF_LIVING VARCHAR(32),
    PRIMARY KEY (NAME, SURNAME, AGE)
)